In [1]:
import numpy as np

In [2]:
a=np.arange(21)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [3]:
a[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
a[3::3]

array([ 3,  6,  9, 12, 15, 18])

In [8]:
#to list 可以達到多層的轉換，而list()只能進行單層的轉換

In [11]:
print(a.ndim)
print(a.size)
print(a.shape)

1
21
(21,)


In [16]:
import numpy as np

c = np.arange(10)
c = c.reshape(2, 5)



def tolist(x):
  if type(x) != np.ndarray :
    return x
  elif type(x) == np.ndarray:
    newlist = []
    for items in x :
      newlist.append(tolist(items))
    return list(newlist)
    
print(tolist(c))


[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]
