In [1]:
import numpy as np

In [2]:
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.arange(2, 11, 2)

array([ 2,  4,  6,  8, 10])

In [4]:
np.arange(3, 11, 3)

array([3, 6, 9])